import { SYSTEMS } from "../utils/constants";
import { timeToMinutes } from "../utils/time";
import { createDefaultState } from "../store/defaultState";

/**
 * parsePlan
 * ---------
 * Converts a structured text plan (as generated by an AI Chief of Staff)
 * into a plain object matching the app's state shape.
 *
 * The parser is intentionally forgiving: a malformed or missing section is
 * reported back as a human-readable note rather than thrown as an error,
 * so a slightly imperfect plan still loads instead of blocking the morning.
 *
 * Expected sections (see /docs or the Import page's "See expected format"
 * for a full example):
 *
 *   MISSION: <text>
 *   WIN: <text>
 *   TOP3:
 *   - <task>
 *   TIMELINE:
 *   HH:MM | duration_min | task | system | purpose | priority | notes
 *   SYSTEMS:
 *   <System Name>: weekly | monthly | yearly
 *   STATS:
 *   <stat_key>: done|pending   OR   current/goal
 *   WIN STREAK: <number>
 *   CYBER STREAK: <number>
 *   READING STREAK: <number>
 *   FITNESS STREAK: <number>
 *
 * Note: today's per-system % is never read from SYSTEMS — it's calculated
 * automatically from which timeline tasks are checked off (see
 * utils/systems.js: computeTodayPct / getSystemProgress). The AI only needs
 * to supply the mission, timeline, and priorities; Northstar derives today's
 * numbers itself, so they can never drift from what actually got done.
 *
 * Future: once ChatGPT can call Northstar's API directly, this same function
 * (or a JSON-shaped sibling of it) is the integration point — the transport
 * changes, the parsing contract does not.
 */
export function parsePlan(raw) {
  const errors = [];
  const result = createDefaultState();

  const sectionMap = {};
  let section = null;

  const lines = raw.split("\n");
  for (const rawLine of lines) {
    const trimmed = rawLine.trim();
    if (!trimmed) continue;

    if (/^TOP3:?$/.test(trimmed)) { section = "TOP3"; sectionMap.TOP3 = sectionMap.TOP3 || []; continue; }
    if (/^TIMELINE:?$/.test(trimmed)) { section = "TIMELINE"; sectionMap.TIMELINE = sectionMap.TIMELINE || []; continue; }
    if (/^SYSTEMS:?$/.test(trimmed)) { section = "SYSTEMS"; sectionMap.SYSTEMS = sectionMap.SYSTEMS || []; continue; }
    if (/^STATS:?$/.test(trimmed)) { section = "STATS"; sectionMap.STATS = sectionMap.STATS || []; continue; }

    // Generic "KEY: value" line, where KEY can be multi-word and all caps
    // (MISSION, WIN, WIN STREAK, CYBER STREAK, READING STREAK, FITNESS
    // STREAK, and any legacy STREAK line). Section headers are matched above
    // first, so this only ever catches inline fields.
    const inlineMatch = trimmed.match(/^([A-Z][A-Z ]*):\s*(.*)$/);
    if (inlineMatch) {
      sectionMap[inlineMatch[1].trim()] = inlineMatch[2];
      section = null;
      continue;
    }

    if (section === "TOP3") {
      const m = trimmed.match(/^-\s*(.+)$/);
      if (m) sectionMap.TOP3.push(m[1].trim());
    } else if (section === "TIMELINE") {
      sectionMap.TIMELINE.push(trimmed);
    } else if (section === "SYSTEMS") {
      sectionMap.SYSTEMS.push(trimmed);
    } else if (section === "STATS") {
      sectionMap.STATS.push(trimmed);
    }
  }

  parseHeader(sectionMap, result, errors);
  parseTop3(sectionMap, result, errors);
  parseTimeline(sectionMap, result, errors);
  parseSystems(sectionMap, result, errors);
  parseStats(sectionMap, result, errors);

  result.sideways = false;
  result.lastImportedAt = new Date().toISOString();

  return { data: result, errors };
}

const STREAK_FIELDS = [
  { key: "WIN STREAK", target: "win" },
  { key: "CYBER STREAK", target: "cyber" },
  { key: "READING STREAK", target: "reading" },
  { key: "FITNESS STREAK", target: "fitness" },
];

function parseHeader(sectionMap, result, errors) {
  if (sectionMap.MISSION) result.mission = sectionMap.MISSION.trim();
  else errors.push("No MISSION found — kept the previous mission.");

  if (sectionMap.WIN) result.winCondition = sectionMap.WIN.trim();
  else errors.push("No WIN condition found.");

  let foundAny = false;
  STREAK_FIELDS.forEach(({ key, target }) => {
    if (sectionMap[key] !== undefined) {
      foundAny = true;
      const n = parseInt(sectionMap[key], 10);
      if (!Number.isNaN(n)) result.streaks[target] = n;
    }
  });

  // Backward compatibility: a bare STREAK: line (the old single-metric
  // format) is treated as the win streak.
  if (sectionMap.STREAK !== undefined) {
    const n = parseInt(sectionMap.STREAK, 10);
    if (!Number.isNaN(n)) result.streaks.win = n;
    errors.push(
      "STREAK is now four metrics — WIN STREAK, CYBER STREAK, READING STREAK, FITNESS STREAK. Parsed STREAK as the win streak for compatibility."
    );
    foundAny = true;
  }

  if (!foundAny) {
    errors.push("No streak values found — defaulted to 0.");
  }
}

function parseTop3(sectionMap, result, errors) {
  if (sectionMap.TOP3 && sectionMap.TOP3.length) {
    result.top3 = sectionMap.TOP3.map((text, i) => ({
      id: `top3-${i}`,
      text,
      done: false,
    }));
  } else {
    errors.push("No TOP3 section found.");
  }
}

function parseTimeline(sectionMap, result, errors) {
  if (!sectionMap.TIMELINE || !sectionMap.TIMELINE.length) {
    errors.push("No TIMELINE section found — the timeline will be empty.");
    return;
  }

  result.timeline = sectionMap.TIMELINE.map((line, i) => {
    const parts = line.split("|").map((p) => p.trim());
    const [time, duration, task, system, purpose, priority, notes] = parts;

    const startMin = timeToMinutes(time || "");
    if (startMin === null) {
      errors.push(`Timeline row ${i + 1}: could not parse time "${time}".`);
    }

    const dur = parseInt(duration, 10);
    const notesText = notes || "";
    const skippable = /\[skip\]/i.test(notesText);
    const depsMatch = notesText.match(/deps:\s*(.+)$/i);
    const dependencies = depsMatch ? depsMatch[1].trim() : "";
    const cleanNotes = notesText
      .replace(/\[skip\]/i, "")
      .replace(/deps:\s*.+$/i, "")
      .trim();

    return {
      id: `block-${i}-${time}`,
      time: time || "--:--",
      startMin: startMin === null ? i * 60 : startMin,
      duration: Number.isNaN(dur) ? 30 : dur,
      task: task || "Untitled task",
      system: SYSTEMS.includes(system) ? system : system || "Home",
      purpose: purpose || "",
      priority: (priority || "medium").toLowerCase(),
      notes: cleanNotes,
      skippable,
      dependencies,
      checked: false,
      movedToTomorrow: false,
    };
  }).sort((a, b) => a.startMin - b.startMin);
}

function parseSystems(sectionMap, result, errors) {
  if (!sectionMap.SYSTEMS || !sectionMap.SYSTEMS.length) {
    errors.push(
      "No SYSTEMS section found — weekly/monthly/yearly will show 0%. Today's progress is always calculated automatically from completed tasks."
    );
    return;
  }

  sectionMap.SYSTEMS.forEach((line) => {
    const m = line.match(/^([^:]+):\s*(.+)$/);
    if (!m) return;
    const name = m[1].trim();

    if (!SYSTEMS.includes(name)) {
      errors.push(`Unknown system "${name}" — skipped.`);
      return;
    }

    const vals = m[2]
      .split("|")
      .map((v) => parseFloat(v.trim()))
      .filter((v) => !Number.isNaN(v));

    // Format is "weekly | monthly | yearly". Today is never read from here —
    // it's computed live from the timeline (see utils/systems.js). A legacy
    // 4-value line (today | weekly | monthly | yearly) is still accepted;
    // the leading value is simply ignored.
    let weekly, monthly, yearly;
    if (vals.length >= 4) {
      [, weekly, monthly, yearly] = vals;
      errors.push(
        `"${name}" included a manual today value — ignored, since today's progress is now calculated automatically.`
      );
    } else {
      [weekly, monthly, yearly] = vals;
    }

    result.systems[name] = {
      weekly: weekly ?? 0,
      monthly: monthly ?? weekly ?? 0,
      yearly: yearly ?? weekly ?? 0,
    };
  });
}

function parseStats(sectionMap, result, errors) {
  if (!sectionMap.STATS || !sectionMap.STATS.length) {
    errors.push("No STATS section found.");
    return;
  }

  sectionMap.STATS.forEach((line) => {
    const m = line.match(/^([a-zA-Z0-9]+):\s*(.+)$/);
    if (!m) return;
    const key = m[1].trim().toLowerCase();
    const val = m[2].trim();

    if (!(key in result.stats)) return;

    if (typeof result.stats[key] === "string") {
      result.stats[key] = /done|complete|yes|true/i.test(val) ? "done" : "pending";
    } else {
      const fractionMatch = val.match(/^(\d+)\s*\/\s*(\d+)/);
      if (fractionMatch) {
        result.stats[key] = {
          current: parseInt(fractionMatch[1], 10),
          goal: parseInt(fractionMatch[2], 10),
        };
      }
    }
  });
}

// This example represents Day 1: no history exists yet, so weekly/monthly/
// yearly progress and every streak start at zero. They only grow once real
// days get completed. A plan generated on day 15, for instance, would carry
// whatever weekly/monthly/yearly and streak numbers actually happened.
export const EXAMPLE_PLAN = `MISSION: Build Momentum
WIN: Ship the incident postmortem and finish Cyber Lab 12
TOP3:
- Finish incident postmortem write-up
- Complete Cybersecurity Lab 12
- 30 min investing research

TIMELINE:
06:00 | 30 | Morning routine | Health | Hydrate, stretch, sunlight | high |
06:30 | 60 | Deep work: automation backlog | Work Excellence | Builder-mode prep before standup | high |
08:30 | 60 | Standup + incident queue | Career | Operations mode begins | high | deps: Deep work block
09:30 | 90 | Incident response + escalations | Career | Handle open tickets | medium |
11:00 | 30 | Reportee 1:1 | Career | Coaching check-in | medium | [skip]
12:00 | 45 | Lunch + walk | Health | Reset before afternoon | low |
15:30 | 60 | Builder mode: Copilot Studio flow | Work Excellence | Ship automation v2 | high |
17:00 | 45 | Cybersecurity Lab 12 | Cybersecurity | OSINT lab | high |
18:00 | 30 | Workout | Health | Strength day | high |
19:00 | 30 | Dinner + meal prep | Home | Prep tomorrow's lunches | medium |
20:00 | 30 | Investing research | Wealth Management | Read 10-K notes | medium |
20:30 | 20 | Evening journal | Mindset | Reflect and close the day | low |

SYSTEMS:
Health: 0 | 0 | 0
Career: 0 | 0 | 0
Work Excellence: 0 | 0 | 0
Cybersecurity: 0 | 0 | 0
Computer Science Exploration: 0 | 0 | 0
Culture Exploration: 0 | 0 | 0
Wealth Management: 0 | 0 | 0
Home: 0 | 0 | 0
Mindset: 0 | 0 | 0
Relationships: 0 | 0 | 0

STATS:
water: 0/8
steps: 0/8000
workout1: pending
workout2: pending
cyberday: pending
reading: pending
mealprep: pending

WIN STREAK: 0
CYBER STREAK: 0
READING STREAK: 0
FITNESS STREAK: 0`;
